apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deploymentLabel }}
  ports:
    - name: podport
      protocol: TCP
      port: 8090
      targetPort: 8080